services:
  spring:
    image: "dan984/springp:0.1"
    container_name: spring-serviceprueba
    build:
      context: https://github.com/dan984git/backend-factura.git#master
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://facturaups.database.windows.net:1433;database=facturas
      - SPRING_DATASOURCE_USERNAME=usralx
      - SPRING_DATASOURCE_PASSWORD=sa.123456
  vue:
    image: "contregistryby.azurecr.io/factura"
    container_name: vue-serviceprueba
    build:
      context: https://github.com/dan984git/factura-frontend.git#master
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - spring

volumes:
  db-data:
