# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - facturasups

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_38f51436c88f42c783ca4ddf8736423b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_aed89b01a48f49c49f2243999ef149f7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_38f51436c88f42c783ca4ddf8736423b }}/vuep:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'facturasups'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6a1cccc3bc1f4c49a6ef6a4e257153d6 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_38f51436c88f42c783ca4ddf8736423b }}/vuep:${{ github.sha }}'